vaccineplan/clinics/urls.py
import django.urls

import clinics.views

app_name = "clinics"

urlpatterns = [
    django.urls.path(
        "registration/",
        clinics.views.ClinicRegistrationFormView.as_view(),
        name="registration",
    ),
    django.urls.path(
        "<int:pk>/admin/",
        clinics.views.ClinicAdmin.as_view(),
        name="admin",
    ),
    django.urls.path(
        "<int:pk>/admin/vaccines/",
        clinics.views.clinic_vaccines,
        name="vaccines",
    ),
]

vaccineplan/homepage/urls.py
import django.urls

import homepage.views


app_name = "homepage"

urlpatterns = [
    django.urls.path("", homepage.views.HomepageView.as_view(), name="home"),
]

vaccineplan/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views


app_name = "users"

urlpatterns = [
    django.urls.path(
        "activate/<str:token>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "profile/",
        users.views.profile,
        name="profile",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<str:uidb64>/<str:token>",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    django.urls.path(
        "signup/",
        users.views.SignupFormView.as_view(),
        name="signup",
    ),
]

vaccineplan/vaccineplan/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include("homepage.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("users.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("django.contrib.auth.urls"),
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "clinics/",
        django.urls.include("clinics.urls"),
    ),
    django.urls.path(
        "vaccines/",
        django.urls.include("vaccines.urls"),
    ),
    django.urls.path(
        "vaccine_calendar/",
        django.urls.include("vaccine_calendar.urls"),
    ),
    django.urls.path(
        "feedback/",
        django.urls.include("feedback.urls"),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.STATIC_URL,
    document_root=django.conf.settings.STATIC_ROOT,
)
urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    )

vaccineplan/users/models.py
import pathlib

import django.contrib.auth.models
import django.core.validators
import django.db.models
import sorl

import clinics.models
import core.models


class CustomUser(django.contrib.auth.models.AbstractUser):
    def get_avatar_path(self, filename):
        return (
            pathlib.Path("users") / f"avatar_user_{str(self.user.id)}"
            f".{filename.split('.')[-1]}"
        )

    class GenderChoices(django.db.models.TextChoices):
        MALE = ("M", "мужской")
        FEMALE = ("F", "женский")

    gender = django.db.models.CharField(
        "пол",
        max_length=1,
        choices=GenderChoices.choices,
    )

    birthday = django.db.models.DateField(
        "дата рождения",
        blank=True,
        null=True,
    )

    image = django.db.models.ImageField(
        "аватарка",
        blank=True,
        null=True,
        upload_to="users/%Y/%m/%d/",
    )

    middle_name = django.db.models.CharField(
        "отчество",
        blank=True,
        null=True,
        max_length=128,
    )

    admins_clinic = django.db.models.ForeignKey(
        to=clinics.models.Clinics,
        verbose_name="администрируемая клиника",
        help_text="клиника, которой администрирует пользователь",
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="admins_clinic",
    )

    clinic = django.db.models.ForeignKey(
        to=clinics.models.Clinics,
        verbose_name="клиника",
        help_text="клиника, к которой прикреплен пользователь",
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="clinic",
    )

    featured_clinics = django.db.models.ManyToManyField(
        to=clinics.models.Clinics,
        verbose_name="отслеживаемые клиники",
        help_text="клиники, которые выбрал пользователь для отслеживания",
        related_name="featured_clinics",
    )

    city = django.db.models.ForeignKey(
        to=core.models.City,
        verbose_name="город",
        help_text="город проживания пользователя",
        on_delete=django.db.models.deletion.CASCADE,
        default=613,
    )

    def get_image_x300(self):
        return sorl.thumbnail.get_thumbnail(
            self.image,
            "300x300",
            crop="center",
            quality=51,
        )

    def image_tmb(self):
        if self.image:
            return django.utils.safestring.mark_safe(
                f'<img src="{self.get_image_x300().url}">',
            )
        return "изображения нет"

    image_tmb.short_description = "превью (300x300)"
    image_tmb.allow_tags = True

vaccineplan/users/forms.py
import django.contrib.auth.forms
import django.contrib.auth.models
import django.forms
import django.forms.fields

import clinics.models
import users.models


__all__ = []


class SignUpForm(django.contrib.auth.forms.UserCreationForm):
    email = django.forms.EmailField(
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            users.models.CustomUser.birthday.field.name
        ].widget = django.forms.fields.TextInput(
            {
                "type": "date",
            },
        )

    class Meta:
        model = users.models.CustomUser
        fields = [
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
            users.models.CustomUser.middle_name.field.name,
            users.models.CustomUser.city.field.name,
            users.models.CustomUser.gender.field.name,
            users.models.CustomUser.birthday.field.name,
        ]


class ProfileForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            users.models.CustomUser.birthday.field.name
        ].widget = django.forms.fields.TextInput(
            {
                "type": "date",
            },
        )
        self.fields[
            users.models.CustomUser.image.field.name
        ].widget = django.forms.FileInput()
        self.fields["clinic"] = django.forms.ModelChoiceField(
            clinics.models.Clinics.objects.filter(approved=True),
        )
        self.fields["clinic"].required = False

    class Meta:
        model = users.models.CustomUser
        fields = [
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
            users.models.CustomUser.middle_name.field.name,
            users.models.CustomUser.birthday.field.name,
            users.models.CustomUser.city.field.name,
            users.models.CustomUser.image.field.name,
            users.models.CustomUser.clinic.field.name,
        ]

vaccineplan/users/views.py
import datetime

import django.conf
import django.contrib.auth
import django.contrib.auth.decorators
import django.contrib.auth.mixins
import django.contrib.auth.models
import django.contrib.messages
import django.core.mail
import django.shortcuts
import django.urls
import django.utils.timezone
import django.views.generic
import jwt

import clinics.models
import core.utils
import users.forms
import users.models


__all__ = []


@django.contrib.auth.decorators.login_required
def profile(request):
    template = "users/profile.html"
    user = request.user
    form = users.forms.ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=user,
        initial={
            "birthday": user.birthday,
            "image": user.image,
        },
    )

    if request.method == "POST":
        if form.is_valid():
            form.save()
            django.contrib.messages.success(
                request,
                "Данные профиля успешно обновлены",
            )
            return django.shortcuts.redirect("users:profile")
        django.contrib.messages.warning(
            request,
            "Некорректные данные",
        )
        return django.shortcuts.redirect("users:profile")

    context = {
        "form": form,
    }

    is_admin = clinics.models.Clinics.objects.filter(
        admin_id=request.user,
    ).exists()
    if is_admin:
        admins_clinic_id = clinics.models.Clinics.objects.get(
            admin_id=request.user,
        ).id
        context["admins_clinic_id"] = admins_clinic_id
    context["is_admin"] = is_admin

    return django.shortcuts.render(request, template, context)


class SignupFormView(django.views.generic.FormView):
    template_name = "users/signup.html"
    form_class = users.forms.SignUpForm

    def form_valid(self, form):
        user = form.save()
        user.save()

        if django.conf.settings.DEFAULT_USER_IS_ACTIVE:
            user.is_active = True
            user.save()

        expiration = django.utils.timezone.now() + datetime.timedelta(
            hours=django.conf.settings.LINK_EXPIRATION,
        )

        exp_timestamp = int(expiration.timestamp())

        token_context = {
            "username": user.username,
            "exp": exp_timestamp,
        }

        token = jwt.encode(
            token_context,
            django.conf.settings.SECRET_KEY,
            algorithm="HS256",
        )

        activation_link = self.request.build_absolute_uri(
            django.urls.reverse(
                "users:activate",
                kwargs={
                    "token": token,
                },
            ),
        )

        msg_text = (
            f"Вам необходимо активировать аккаунт в течение 12 "
            "часов после регистрации. "
            "Для активации перейдите по ссылке, указанной в"
            " данном письме.\n"
            f"Ссылка для активации: {activation_link}"
        )

        django.core.mail.send_mail(
            "Активация аккаунта VaccinePlan",
            msg_text,
            django.conf.settings.EMAIL_ADDRESS,
            [user.email],
        )

        django.contrib.auth.login(self.request, user)

        return django.shortcuts.redirect(
            django.urls.reverse("homepage:home"),
        )


class ActivateUserView(django.views.generic.TemplateView):
    template_name = "users/activation_success.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token = self.kwargs["token"]
        data, status_ok = core.utils.decode_token(token)

        if status_ok:
            try:
                user = users.models.CustomUser.objects.get(
                    username=data["username"],
                )
                user.is_active = True
                user.save()
                context["ok"] = status_ok
                context["info"] = data
            except users.models.CustomUser.DoesNotExist:
                context["ok"] = False
                context["info"] = "Пользователь не найден"
        else:
            context["ok"] = status_ok
            context["info"] = data

        return context

vaccineplan/templates/users/activation_success.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Аккаунт активирован
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Активация аккаунта</h1>
<div class="container d-flex justify-content-center">
  <div class="alert {% if ok %}alert-success{% else %}alert-danger{% endif %}">
    <h1 class="alert-heading">{% if ok %}Аккаунт успешно активирован!{% else %}{{ info }}{% endif %}</h1>
    <p>{% if ok %}Ваш аккаунт активирован, а ссылка для активации больше недействительна{% else %}Упс! Что-то пошло не так{% endif %}</p>
    <div class="d-grid gap-2 my-2">
      <a class="btn btn-outline-{% if ok %}success{% else %}danger{% endif %}" href="{% url 'homepage:home' %}">На главную</a>
    </div>
  </div>
</div>

{% endblock %}

vaccineplan/templates/users/login.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Авторизация
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Авторизация пользователя</h1>

{% include "includes/form.html" with submit_value="Войти" %}

{% endblock %}

vaccineplan/templates/users/logout.html
{% extends "base.html" %}

{% load static %}

<div class="container d-flex justify-content-center">
  <div class="w-50">
    <h1 class="fs-2 fw-bold text-center">Вы вышли из аккаунта. Будем ждать Вас снова!</h1>
    <p class="fs-5 text-muted">Вы всегда можете передумать</p>
    <a class="btn d-grid gap-2 btn-lg btn-primary" href="{% url 'homepage:home' %}">На главную</a>
  </div>
</div>

vaccineplan/templates/users/password_change.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Смена пароля
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Смена пароля</h1>

{% include "includes/form.html" with submit_value="Отправить" %}

{% endblock %}

vaccineplan/templates/users/password_change_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Смена пароля
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Успешно!</h1>
<div class="container d-flex justify-content-center">
  <div class="w-50">
    <div class="alert alert-success">
      <p>Ура</p>
      <p>Пароль изменен</p>
    </div>
  </div>
</div>

{% endblock %}

vaccineplan/templates/users/password_reset.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Восстановление пароля
{% endblock %}

{% block content %}
<h1 class="fs-2 fw-bold text-center">Восстановление пароля</h1>

{% include "includes/form.html" with submit_value="Подтвердить" %}

{% endblock %}

vaccineplan/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Смена пароля
{% endblock %}

{% block content %}

{% if validlink %}

<h1 class="fs-2 fw-bold text-center">Пароль успешно изменён</h1>
<div class="container d-flex justify-content-center">
  <div class="w-50">
    <div class="alert alert-success">
      <h1 class="alert-heading">Можете пользоваться новым паролем!</h1>
      <p>Удачного пользования сервисом</p>
    </div>
  </div>
</div>

{% else %}

<h1 class="fs-2 fw-bold text-center">Упс!</h1>
<div class="container d-flex justify-content-center">
  <div class="w-50">
    <div class="alert alert-success">
      <h1 class="alert-heading">Ссылка больше недействительна</h1>
      <p>Вероятно, у неё истёк период действия, или ей уже воспользовались :(</p>
    </div>
  </div>
</div>

{% endif %}

{% endblock %}

vaccineplan/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Восстановление пароля
{% endblock %}

{% block content %}
<h1 class="fs-2 fw-bold text-center">Придумайте новый пароль</h1>

{% include "includes/form.html" with submit_value="Подтвердить" %}

{% endblock %}

vaccineplan/templates/users/password_reset_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Восстановление пароля
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Письмо отправлено!</h1>
<div class="container d-flex justify-content-center">
  <div class="w-50">
    <div class="alert alert-success">
      <p>Проверьте электронную почту</p>
      <p>Если вам не приходит письмо, проверьте, корректно ли вы заполнили данные эл. почты</p>
    </div>
  </div>
</div>

{% endblock %}

vaccineplan/templates/users/profile.html
{% extends "base.html" %}

{% load static thumbnail widget_tweaks %}

{% block title %}
Мой Профиль
{% endblock %}

{% block content %}

<h1 class="fs-1 fw-bold text-center">Профиль</h1>

<form method="post" enctype="multipart/form-data">

  {% csrf_token %}

  <div class="my-2 row">
    <div class="col-3 col-mb-4">

      {% if request.user.image %}

      {% thumbnail request.user.image "400x400" crop="center" as img %}

      <a href="{{ img.url }}">
        <img src="{{ img.url }}" class="rounded img-thumbnail" alt="Аватарка пользователя">
      </a>

      {% endthumbnail %}

      {% else %}

      <img src="{% static 'img/image_filler.png' %}" class="rounded img-thumbnail" alt="Аватарка пользователя">

      {% endif %}
      
        <div class="my-1 mx-1 d-grid gap-2">
          {{ form.image|add_class:"form-control" }}
        </div>
        
        <div class="d-grid gap-2 my-2">
          {% if user.is_active %}<span class="fs-6 badge bg-success">Аккаунт активирован</span>{% else %}<span class="fs-6 badge bg-danger">Аккаунт не активирован</span>{% endif %}
        </div>
      </div>

    <div class="col-6">

      {% if messages %}
      
      <div class="alert alert-dark my-1">
        {% for message in messages %}
        <p class="text-center">{{ message }}</p>
        {% endfor %}
      </div>

      {% endif %}

      {% for field in form.visible_fields %}

      {% if field.name != "image" %}

      <div class="my-2">

        {% for error in field.errors %}

        <div class="my-1 alert alert-danger">
          {{ error|escape }}
        </div>

        {% endfor %}

      </div>

      <div class="form-floating my-2">
        {{ field|add_class:"form-control" }}
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
      </div>

      {% endif %}

      {% endfor %}

      <div class="d-flex justify-content-end">
        <button class="btn btn-primary my-2" type="submit">Сохранить изменения</button>
      </div>
      
    </div>

    <div class="col container-relative">
      <div class="my-1">
        <div class="d-grid gap-2">
          <a class="btn btn-outline-primary" href="{% url 'users:password_change' %}">Сменить пароль</a>
        </div>
      </div>
      {% if not is_admin and user.is_active %}
      <div class="my-3">
        <div class="d-grid gap-2">
          <a class="btn btn-outline-success my-1" href="{% url 'clinics:registration' %}">Зарегистрировать клинику</a>
        </div>    
      </div>
      {% endif %}
      {% if is_admin %}
      <div class="my-3">
        <div class="d-grid gap-2">
          <a class="btn btn-warning my-1" href="{% url 'clinics:admin' pk=admins_clinic_id %}">Администрировать клинику</a>
        </div>    
      </div>
      {% endif %}
    </div>
  </div>

</form>

{% endblock %}

vaccineplan/templates/users/signup.html
{% extends "base.html" %}

{% load static widget_tweaks %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}

<h1 class="fs-2 fw-bold text-center">Регистрация</h1>

{% include "includes/form.html" with submit_value="Зарегистрироваться" %}

{% endblock %}