vaccineplan/feedback/urls.py
import django.urls

import feedback.views

app_name = "feedback"

urlpatterns = [
    django.urls.path(
        "",
        feedback.views.FeedbackFormView.as_view(),
        name="feedback",
    ),
]

vaccineplan/homepage/urls.py
import django.urls

import homepage.views


app_name = "homepage"

urlpatterns = [
    django.urls.path("", homepage.views.HomepageView.as_view(), name="home"),
]

vaccineplan/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views


app_name = "users"

urlpatterns = [
    django.urls.path(
        "activate/<str:token>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "profile/",
        users.views.profile,
        name="profile",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<str:uidb64>/<str:token>",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    django.urls.path(
        "signup/",
        users.views.SignupFormView.as_view(),
        name="signup",
    ),
]

vaccineplan/vaccine_calendar/urls.py
import django.urls

import vaccine_calendar.views


app_name = "vaccine_calendar"

urlpatterns = [
    django.urls.path(
        "",
        vaccine_calendar.views.VaccineCalendarView.as_view(),
        name="calendar",
    ),
    django.urls.path(
        "record/<int:pk>",
        vaccine_calendar.views.RecordView.as_view(),
        name="record",
    ),
    django.urls.path(
        "record/<int:pk>/delete",
        vaccine_calendar.views.RecordDeleteView.as_view(),
        name="record_delete",
    ),
]

vaccineplan/vaccineplan/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include("homepage.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("users.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("django.contrib.auth.urls"),
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "clinics/",
        django.urls.include("clinics.urls"),
    ),
    django.urls.path(
        "vaccines/",
        django.urls.include("vaccines.urls"),
    ),
    django.urls.path(
        "vaccine_calendar/",
        django.urls.include("vaccine_calendar.urls"),
    ),
    django.urls.path(
        "feedback/",
        django.urls.include("feedback.urls"),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.STATIC_URL,
    document_root=django.conf.settings.STATIC_ROOT,
)
urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    )

vaccineplan/vaccines/urls.py
import django.urls

import vaccines.views


app_name = "vaccines"

urlpatterns = [
    django.urls.path(
        "<int:pk>/",
        vaccines.views.VaccinesView.as_view(),
        name="vaccine_info",
    ),
]

vaccineplan/templates/includes/accordion_checkboxes.html
<li class="list-group-item">
    <input type="checkbox" id="{{ vaccine.id }}"
                name="vaccines" value="{{ vaccine.id }}"
                {% if vaccine.id in already_checked %} checked {% endif %}>
    <label for="{{ vaccine.id }}">{{ vaccine.name }}</label>
</li>

vaccineplan/templates/includes/availability_card.html
<div class="col-12">
  <div class="card my-3 shadow">
    <div class="card-body">
      <div class="border-bottom">
        <a class="text-decoration-none card-title fs-5 fw-bold" href="{% url 'vaccine_calendar:record' availability.id %}">{{ availability.vaccines.name }}</a>
      </div>
      <div class="card-text fs-6 text-muted">
      	{{ availability.clinic.address|safe }}
      </div>
      <div class="card-text fs-6 text-muted">
        {{ availability.clinic.clinic_mail|safe }}
      </div>
      <div class="card-text fs-6 text-muted">
      	{{ availability.clinic.phone_number|safe }}
      </div>
    </div>
  </div>
</div>

vaccineplan/templates/includes/footer.html
{% load static %}
{% load i18n %}

<div class="p-3 my-4 mb-0">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link px-2 text-muted">Главная страница</a></li>
    <li class="nav-item"><a href="{% url 'vaccine_calendar:calendar' %}" class="nav-link px-2 text-muted">Календарь прививок</a></li>
    <li class="nav-item"><a href="{% url 'feedback:feedback' %}" class="nav-link px-2 text-muted">Обратная связь</a></li>
  </ul>
  <div class="row">
    <div class="col">
      <p class="text-muted text-center">Команда 5, {% now "Y" %}</p>
    </div>
  </div>
</div>

vaccineplan/templates/includes/form.html
{% load static widget_tweaks %}

<div class="container d-flex justify-content-center">
  <div class="w-50">
    <form method="post" enctype="multipart/form-data">
      
      {% csrf_token %}

      <div class="my-2">

        {% for field in form.visible_fields %}

        <div class="my-2">

          {% for error in field.errors %}

          <div class="my-1 alert alert-danger">

            {{ error|escape }}

          </div>

          {% endfor %}

        </div>

        <div class="my-2">

          <div class="form-floating">
            {{ field|add_class:"form-control" }}
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
          </div>

          {% if field.help_text %}

          <p class="fs-6 text-muted">{{ field.help_text }}</p>

          {% endif %}
        
        </div>

        {% endfor %}

      </div>

      {% if form.non_field_errors %}

        <div class="alert alert-danger my-2">
          <h4 class="alert-heading">Ошибка</h4>

          {% for error in form.non_field_errors %}

          <p>{{ error|escape }}</p>

          {% endfor %}

        </div>

      {% endif %}

      <div class="my-2">
        <button type="submit" class="btn btn-primary">{{ submit_value }}</button>

        {% with request.resolver_match.view_name as view_name %}

        {% if view_name == "users:login" %}

        <a class="btn btn-outline-secondary mx-2" href="{% url 'users:password_reset' %}">Забыли пароль?</a>

        {% elif view_name == "users:signup" %}

        <a class="btn btn-outline-secondary mx-2" href="{% url 'users:login' %}">Уже есть аккаунт?</a>

        {% endif %}

        {% endwith %}
      </div>
    </form>
  </div>
</div>

vaccineplan/templates/includes/header.html
{% load static %}
{% load i18n %}

<div class="container">

  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="{% url 'homepage:home' %}" class="fs-3 fw-bold text-white text-decoration-none">
        <img class="bi me-2" width="32" height="32" src="{% static "img/vaccine.png" %}">
        VaccinePlan
      </a>
    </div>

    {% with request.resolver_match.view_name as view_name %}

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-item">
          <a href="{% url 'homepage:home' %}" class="nav-link px-3 {% if view_name == 'homepage:home' %}text-secondary disabled{% else %}text-white{% endif %}">Главная страница</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'vaccine_calendar:calendar' %}" class="nav-link px-3 {% if view_name == 'vaccine_calendar:calendar' %}text-secondary disabled{% else %}text-white{% endif %}">Календарь прививок</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'feedback:feedback' %}" class="nav-link px-3 {% if view_name == 'feedback:feedback' %}text-secondary disabled{% else %}text-white{% endif %}">Обратная связь</a>
        </li>
        
        {% if user.is_superuser %}

        <li class="nav-item">
          <a href="{% url 'admin:index' %}" class="nav-link px-3">Админка</a>
        </li>

        {% endif %}
      
      </ul>

    {% endwith %}

    <div class="col-md-3 text-end">

      {% if not user.is_authenticated %}

      <a class="btn btn-sm btn-outline-success" href="{% url 'users:signup' %}">Зарегистрироваться</a>
      <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login' %}">Войти</a>

      {% else %}

      <div class="dropdown">
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        {{ user.first_name }} {{ user.last_name }}
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
          {% if user.is_clinic_admin %}
          <li><a class="dropdown-item" href="{% url '#' %}">Администрирование клиники</a></li>
          {% endif %}
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
        </ul>
      </div>

      {% endif %}
      
    </div>
  </div>
</div>

vaccineplan/templates/includes/illness_card.html
<div class="col-6 col-sm-6 col-md-4 col-xl-3 d-flex align-items-stretch">
  <div class="card my-3 shadow">
    <div class="card-body">
      <div class="border-bottom pb-2">
        <a class="text-decoration-none card-title fs-5 fw-bold" href="{% url 'vaccines:vaccine_info' illness.id %}">{{ illness.name }}</a>
      </div>
        <div class="card-text fs-6 text-muted">
        {{ illness.description|truncatewords_html:20|safe }}  
      </div>
    </div>
  </div>
</div>

vaccineplan/templates/includes/record_card.html
{% load tz %}


<div class="card my-3 shadow p-3">
  <h2 class="fs-5 fw-bold border-bottom p-2">{{ record.vaccine.name }} {% if record.timetable < now|utc %}<span class="badge bg-danger">Прошедшее</span>{% endif %}</h2>
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col-2">
          <span class="badge bg-secondary">Дата</span>
        </div>
        <div class="col">
          <p class="fs-6 text-muted">{{ record.timetable|date }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-2">
          <span class="badge bg-secondary">Телефон</span>
        </div>
        <div class="col">
          <p class="fs-6 text-muted">{{ record.clinic.phone_number }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-2">
          <span class="badge bg-secondary">Адрес</span>
        </div>
        <div class="col">
          <p class="fs-6 text-muted">{{ record.clinic.address }}</p>
        </div>
      </div>
    </div>
    <div class="d-flex col justify-content-end">
      <a href={% url "vaccine_calendar:record_delete" record.id %} class="btn btn-outline-danger text-center d-flex align-items-center justify-content-center">Удалить</a>
    </div>
  </div>
</div>

vaccineplan/templates/includes/vaccine_accordion.html
</ul>
	</div>
		</div>
			</div>
				</div>
<div class="accordion" id="accordionPanelsStayOpenExample">
	<div class="accordion-item">
		<h2 class="accordion-header">
			<button class="accordion-button" type="button"
				data-bs-toggle="collapse"
				data-bs-target="#panelsStayOpen-collapse{{vaccine.category.id}}"
				aria-expanded="true"
				aria-controls="panelsStayOpen-collapse{{category.category.id}}">
				{{ vaccine.category.name }}
			</button>
		</h2>
		<div id="panelsStayOpen-collapse{{vaccine.category.id}}"
				class="accordion-collapse collapse">
			<div class="accordion-body">
				<ul class="list-group">

vaccineplan/templates/includes/vaccine_card.html
<div class="col-6 col-md-6 col-xl-4">
  <div class="card my-3 shadow">
    <div class="card-body">
      <a class="card-title fs-5" >{{ availability.vaccine.name }}</a>
      <div class="card-text fs-6 text-muted">
      	{{ availability.clinic.address|safe }}
      </div>
      <div class="card-text fs-6 text-muted">
        {{ availability.clinic.clinic_mail|safe }}
      </div>
      <div class="card-text fs-6 text-muted">
      	{{ availability.clinic.phone_number|safe }}
      </div>
    </div>
  </div>
</div>