vaccineplan/feedback/urls.py
import django.urls

import feedback.views

app_name = "feedback"

urlpatterns = [
    django.urls.path(
        "",
        feedback.views.FeedbackFormView.as_view(),
        name="feedback",
    ),
]

vaccineplan/homepage/urls.py
import django.urls

import homepage.views


app_name = "homepage"

urlpatterns = [
    django.urls.path("", homepage.views.HomepageView.as_view(), name="home"),
]

vaccineplan/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views


app_name = "users"

urlpatterns = [
    django.urls.path(
        "activate/<str:token>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "profile/",
        users.views.profile,
        name="profile",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<str:uidb64>/<str:token>",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "password_reset/complete/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    django.urls.path(
        "signup/",
        users.views.SignupFormView.as_view(),
        name="signup",
    ),
]

vaccineplan/vaccine_calendar/urls.py
import django.urls

import vaccine_calendar.views


app_name = "vaccine_calendar"

urlpatterns = [
    django.urls.path(
        "",
        vaccine_calendar.views.VaccineCalendarView.as_view(),
        name="calendar",
    ),
    django.urls.path(
        "record/<int:pk>",
        vaccine_calendar.views.RecordView.as_view(),
        name="record",
    ),
    django.urls.path(
        "record/<int:pk>/delete",
        vaccine_calendar.views.RecordDeleteView.as_view(),
        name="record_delete",
    ),
]

vaccineplan/vaccineplan/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include("homepage.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("users.urls"),
    ),
    django.urls.path(
        "auth/",
        django.urls.include("django.contrib.auth.urls"),
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "clinics/",
        django.urls.include("clinics.urls"),
    ),
    django.urls.path(
        "vaccines/",
        django.urls.include("vaccines.urls"),
    ),
    django.urls.path(
        "vaccine_calendar/",
        django.urls.include("vaccine_calendar.urls"),
    ),
    django.urls.path(
        "feedback/",
        django.urls.include("feedback.urls"),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.STATIC_URL,
    document_root=django.conf.settings.STATIC_ROOT,
)
urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    )

vaccineplan/homepage/views.py
import django.shortcuts
import django.views.generic

import vaccines.models


class HomepageView(django.views.generic.ListView):
    # model = vaccines.models.VaccineCategories
    context_object_name = "illnesses"
    template_name = "homepage/homepage.html"
    queryset = vaccines.models.VaccineCategories.objects.all()

vaccineplan/templates/homepage/homepage.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Главная страница
{% endblock %}

{% block content %}

<div class="container my-2 py-2 px-3">

  <div class="px-2 pb-4">
    <h1 class="display-6 fw-bold text-body-emphasis text-center">Приветствуем Вас на нашем сайте!</h1>
    <div class="col-lg-7 mx-auto">
      <p class="lead mb-2">Наш сервис предоставляет удобную возможность организации вакцинации населения для поликлиник и пациентов</p>
      <div class="row my-1">

        {% if not user.is_authenticated %}
  
        <div class="col">
          <div class="d-grid gap-2">
            <a class="btn btn-outline-success" href="users:login">Войти</a>
          </div>
        </div>
        <div class="col">
          <div class="d-grid gap-2">
            <a class="btn btn-warning" href="{% url 'users:signup' %}">Зарегистрироваться</a>
          </div>
        </div>
      </div>

      {% else %}

      <div class="col">
        <div class="d-grid gap-2">
          <a class="btn btn-outline-primary" href="{% url 'vaccine_calendar:calendar' %}">Перейти к календарю</a>
        </div>
      </div>

      {% endif %}

    </div>
  </div>

  <div class="row p-2 pe-lg-0 pt-lg-3 align-items-center rounded-4 border shadow-lg my-3">
    <h2 class="lead pb-2 border-bottom fs-2">Как мы работаем?</h2>
    <div class="row g-4 pt-0 row-cols-1 row-cols-lg-3">
      <div class="col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3 p-3" style="border-radius: 12px;">
            <img src="{% static 'img/user.svg' %}" width="32" height="32" class="bi">
        </div>
        <h3 class="lead fs-2 fw-semibold">Пользователь</h3>
        <p class="text-muted">Зарегистрированный пользователь получает возможность мониторинга ситуации по вакцинам в своём городе, а так же составлять список вакцинаций на основе того, что имеется в наличии на данный момент.</p>
      </div>
      <div class="col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3 p-3" style="border-radius: 12px;">
          <img src="{% static 'img/clinic.svg' %}" width="32" height="32" class="bi">
        </div>
        <h3 class="lead fs-2 fw-semibold">Поликлиники</h3>
        <p class="text-muted">Пользователи, получившие подтверждение от администрации сервиса могут управлять поликлиникой, изменяя текущий состав вакцин в наличии.</p>
      </div>
      <div class="col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3 p-3" style="border-radius: 12px;">
          <img src="{% static 'img/admin.svg' %}" width="32" height="32" class="bi">
        </div>
        <h3 class="lead fs-2 fw-semibold">Администрирование</h3>
        <p class="text-muted">Администраторы поликлиник получают возможность мониторинга числа пользователей, прикрепленных к их поликлинике, а так же расширенные возможности взаимодействия с ресурсом.</p>
      </div>
    </div>
  </div>

  <div class="row p-2 pe-lg-0 pt-lg-3 align-items-center rounded-4 border shadow-lg my-3">
    <div class="d-grid gap-2">
      <a class="btn btn-outline-primary" data-bs-toggle="collapse" id="collapse-btn" href="#illnesses_collapse" role="button" aria-controls="illnesses_collapse">
        Краткая справка по болезням
      </a>
    </div>
    <div class="collapse my-2" id="illnesses_collapse">
      <div class="row">
        {% for illness in illnesses %}
    
        {% include "includes/illness_card.html" %}
    
        {% empty %}
    
        <div class="alert alert-dark">
          <h4 class="alert-heading">Список болезней пуст</h4>
          <p>Произошла ошибка, попробуйте заглянуть в другое время</p>
        </div>
        {% endfor %}

        {% if illnesses %}
        <div class="d-grid gap-2">
          <a class="btn btn-outline-secondary" data-bs-toggle="collapse" href="#illnesses_collapse" role="button" aria-controls="illnesses_collapse">
            Свернуть
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  
  <div class="row p-2 pe-lg-0 pt-lg-3 align-items-center rounded-4 border shadow-lg my-3">
    <h2 class="lead pb-2 border-bottom fs-2">Остались вопросы или хотите поделиться впечатлениями?</h2>
    <div class="d-grid gap-2 my-2">
      <a class="btn btn-outline-success" href="{% url 'feedback:feedback' %}">Обратная связь</a>
    </div>
  </div>
  
</div>
{% endblock %}